-- 코드를 입력하세요
SELECT G.BOARD_ID, G.WRITER_ID, G.TITLE, G.PRICE, 
    CASE WHEN G.STATUS = "SALE" THEN "판매중"
         WHEN G.STATUS = "RESERVED" THEN "예약중"
            ELSE "거래완료" END AS STATUS
FROM USED_GOODS_BOARD AS G
WHERE G.CREATED_DATE = '2022-10-05'
ORDER BY G.BOARD_ID DESC