 -- 코드를 입력하세요
 SELECT M.MEMBER_NAME, R.REVIEW_TEXT, DATE_FORMAT(R.REVIEW_DATE, "%Y-%m-%d")
 FROM MEMBER_PROFILE M
 JOIN REST_REVIEW R ON R.MEMBER_ID = M.MEMBER_ID
 WHERE M.MEMBER_ID = (
    SELECT MEMBER_ID
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    ORDER BY COUNT(*) desc
    LIMIT 1
 )
 ORDER BY R.REVIEW_DATE, R.REVIEW_TEXT
