-- 코드를 입력하세요
SELECT P.PRODUCT_ID,
        P.PRODUCT_NAME,
        SUM(P.PRICE * O.AMOUNT) AS PROFIT
FROM FOOD_ORDER O
JOIN (SELECT * FROM FOOD_PRODUCT) P ON P.PRODUCT_ID = O.PRODUCT_ID
WHERE O.PRODUCE_DATE LIKE '2022-05%'
GROUP BY O.PRODUCT_ID
ORDER BY PROFIT DESC, P.PRODUCT_ID;
