SELECT 
    i.REST_ID,
    i.REST_NAME,
    i.FOOD_TYPE, 
    i.FAVORITES,
    i.ADDRESS,
    ROUND(avg(r.REVIEW_SCORE), 2) as SCORE
FROM REST_INFO i 
INNER JOIN REST_REVIEW r on i.REST_ID = r.REST_ID
WHERE i.ADDRESS like '서울%'
GROUP BY i.REST_ID, i.REST_NAME, i.FOOD_TYPE, i.FAVORITES, i.ADDRESS
ORDER BY SCORE desc, i.FAVORITES desc;
